/**
 * Generated by scripts/sync-onnx-runtime.mjs. Do not edit.
 *
 * The installed onnxruntime-web versions, which are also the path segments their
 * WebAssembly builds are served under so they can be cached immutably.
 *
 * Normally there is exactly one, held there by an npm override — see the script
 * for why more than one is a problem rather than a convenience.
 */
export const ORT_VERSION = '1.27.0';
