/**
 * Generated by scripts/sync-onnx-runtime.mjs. Do not edit.
 *
 * The installed onnxruntime-web version, which is also the path segment its
 * WebAssembly build is served under so it can be cached immutably.
 */
export const ORT_VERSION = '1.27.0';
