/**
 * Generated by scripts/sync-onnx-runtime.mjs. Do not edit.
 *
 * The installed onnxruntime-web versions, which are also the path segments their
 * WebAssembly builds are served under so they can be cached immutably.
 *
 * There are two because transformers.js pins its own copy of the runtime and the
 * glue must match the binary it loads. See the script for why that is left alone.
 */
export const ORT_VERSION = '1.27.0';
export const ORT_TRANSFORMERS_VERSION = '1.26.0-dev.20260416-b7804b056c';
