/**
 * Generated by scripts/sync-transformers.mjs. Do not edit.
 *
 * The installed transformers.js version, which is also the path segment its
 * browser build is served under so it can be cached immutably.
 *
 * It is served as a static file and imported by URL rather than bundled — see the
 * script for the bug that forces this.
 */
export const TRANSFORMERS_VERSION = '4.2.0';
