/**
 * Generated by scripts/sync-ffmpeg-core.mjs. Do not edit.
 *
 * The installed @ffmpeg/core version, which is also the path segment the core is
 * served under, so it can be cached immutably.
 */
export const FFMPEG_CORE_VERSION = '0.12.10';
